host: localhost
port: 4000
baseurl: /notoma/

ga_tracking: 

exclude:
  - .idea/
  - .gitignore
  - vendor

# remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"
 
highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
