name: Linters
on: [push, pull_request]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8"]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python}}
        architecture: 'x64'

    - name: Install dev dependencies
      run: |
        pip install poetry
        poetry install

    - name: Lint the code
      run: |
        poetry run flake8
        poetry run black .

    - name: Lint notebooks
      run: |
        make nbexec
