name: Linters
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install dev dependencies
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Lint the code
      run: |
        pipenv run flake8
        pipenv run black .
