name: Lint
on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Install dev dependencies
      run: |
        pip install poetry
        poetry install

    - name: flake8
      run: poetry run flake8

    - name: black
      run: poetry run black .

    - name: nbexec
      run: make nbexec
